import SerialComm
from time import sleep
ser = SerialComm.SerialComm(port='/dev/ttyUSB0', baudrate=115200, timeout=1)
print ser.login_status()
ser.login('root', 'zilogic')
print ser.login_status()
ser.sendline("ifconfig eth0 172.16.2.150 up")
ser.sendline("ifconfig wlan6 192.168.1.1 up")
sleep(3)
ser.sendline("python HandleService.py")
sleep(3)
print ser.read_out()
ser1 = SerialComm.SerialComm(port='/dev/ttyUSB1', baudrate=115200, timeout=1)
print ser1.login_status()
ser1.login('root', 'zilogic')
print ser1.login_status()
ser1.sendline("ifconfig eth0 172.16.2.180 up")
ser1.sendline("ifconfig wlan7 192.168.50.1 up")
sleep(3)
ser1.sendline("python HandleService.py")
sleep(3)
print ser1.read_out()
sleep(30)
